name: Pytest Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pytest"
  pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out this repository so this job can access it
      - uses: actions/checkout@v2

      # Use Python 3.8.16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.16'

      # Install the langcheck package with dev dependencies
      - name: Install
        run: |
          pip install --upgrade pip
          pip install .[dev]

      # Remove unneeded system libraries to maximize disk space
      # https://github.com/easimon/maximize-build-space/blob/master/action.yml
      # https://github.com/actions/virtual-environments/issues/2840#issuecomment-790492173
      - name: Maximize disk space
        run: |
          echo "Available disk space (before):"
          df -h

          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android

          echo "Available disk space (after):"
          df -h

      # Run integration tests
      - name: Test
        run: |
          python -m pytest -s -vv --durations=0 -m "not optional"

      - name: Test (Optional)
        run: |
          pip install .[optional]
          python -m pytest -s -vv --durations=0 -m "optional"
